[folders]
target_dir = 'D:\Temp\New folder test remove - Copy'

source_dirs = [
  'D:\Temp\New folder test remove - Copy',
  'D:\Cristina\Poze Porto - 12.2020-01.2022',
  'D:\Cristi\rust-utils\imgsorter\test_pics'
]

# TODO 1a: temporar citim din ./test_pics
source_subdir = 'blah'

[options]
dry_run = false
silent = false
source_recursive = false
copy_not_move = true
debug_on = false
min_files_per_dir = 1
