[folders]

# This are the folders where the images to be sorted are located.
# If this option is missing, the directory from which the program is launched will be used.
source_dirs = [
  'D:\Temp\New folder test remove - Copy',
  'D:\Temp\New folder test remove - Copy 2',
  'D:\Temp\New folder test remove - Copy 2 - Copy',
  'invalid_folder'
]

# The destination folder for the sorted files.
# If the destination folder does not exist, it will be created.
# If the destination folder exists, a subfolder called "imgsorted" will be created inside and used.
# If this option is missing, the directory from which the program is launched will be used.
target_dir = 'D:\Temp\New folder test remove - Copy'

# There must be more than this number of files for any given date
#   for a dedicated device subfolder to be created. Otherwise, a separate
#   single folder will be created to hold all these files ("one-offs") together.
# See also the target_oneoffs_subdir_name option.
# Setting it to 0 will effectively disable this functionality
# If this option is missing, the default "1" will be used.
min_files_per_dir = 1

# The name of the folder which will hold all files for any given date,
#   which holds less than or equal the [min_files_per_dir] threshold.
# If this option is missing, the default 'Miscellaneous' will be used.
target_oneoffs_subdir_name = 'Miscellaneous'

[options]

# Whether to do a simulation of the process, without writing any files.
# This will display additional information, like the resulting dir structure,
#   including the total number of devices, files and file size.
# If this option is missing, the default "false" will be used.
dry_run = false

# Whether to print additional information during processing
verbose = false

# Whether to read any subfolders in the source folders.
# This will progressively read all subfolders, including subfolders of subfolders.
# If this option is missing, the default "false" will be used.
source_recursive = true

# Whether files are copied instead of moved to the destination folder.
# If this option is true or missing, files will be *copied* to
#  the destination and the source files will be left untouched.
# If this option is false, files are copied to the destination then DELETED from the source.
copy_not_move = true

# Whether to ask for user confirmation before processing files.
# If this option is missing, the default "false" will be used.
# !! Be careful when using this when "copy_no_move" is true, as files will be moved without confirmation.
silent = false

[custom]

# Replace model names of camera as retrieved from EXIF info with
# custom names for improved clarity, e.g. "Samsung A41" instead of "SM-A415F"
[custom.devices]
#'HUAWEI VNS-L21'="Huawei P9 Lite"
#'SM-A415F'="Samsung A41"

# Additional file extensions to be recognized and processed
# Note: these are not supported and only basic metadata
# will be available (i.e. modified date)
[custom.extensions]
image = [ "heic" ]
video = []
audio = [ "amr"]