[folders]
target_dir = 'D:\Temp\New folder test remove - Copy'

source_dirs = [
    'D:\Temp\New folder test remove - Copy',
    'D:\Temp\New folder test remove - Copy 2',
    'D:\Temp\New folder test remove - Copy 2 - Copy'
]


[options]
dry_run = false
silent = false
source_recursive = true
copy_not_move = true
debug_on = false
min_files_per_dir = 1

# source_dirs = [
#     "D:\Temp\New folder test remove - Copy",
#     "D:\Temp\New folder test remove - Copy 2",
#     "D:\Temp\New folder test remove - Copy 2 - Copy",
# ]